name: Docker Build
on:
  workflow_call: {}
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: [ "mainline" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
permissions:
  contents: read
jobs:
  test:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make docker.stat docker.pynchon.build 
      - name: Smoke-Test
        run: make docker.pynchon.test